rvue/apps/config/routes.rb
Rails.application.routes.draw do
  resources :occupations
  resources :regulations
  resources :calenders
  devise_for :admins, controllers: {
        registration: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  devise_for :users, controllers: {
        registration: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"

end

rvue/apps/app/models/occupation.rb
class Occupation < ApplicationRecord
  belongs_to :user
  belongs_to :room
    scope :owned_by_user, ->(user_id){ where("user_id = ?", user_id) }
end

rvue/apps/app/controllers/occupations_controller.rb
class OccupationsController < ApplicationController
  before_action :set_occupation, only: %i[ show edit update destroy ]

  include CalenderData

  # GET /occupations or /occupations.json
  def index
    @occupations = Occupation.owned_by_user(current_user.id)

    month = params[:month]
    calender_for_view(month)
  end

  # GET /occupations/1 or /occupations/1.json
  def show
  end

  # GET /occupations/new
  def new
    @occupation = Occupation.new
  end

  # GET /occupations/1/edit
  def edit
  end

  # POST /occupations or /occupations.json
  def create
    @occupation = Occupation.new(occupation_params)

    respond_to do |format|
      if @occupation.save
        format.html { redirect_to occupation_url(@occupation), notice: "Occupation was successfully created." }
        format.json { render :show, status: :created, location: @occupation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occupations/1 or /occupations/1.json
  def update
    respond_to do |format|
      if @occupation.update(occupation_params)
        format.html { redirect_to occupation_url(@occupation), notice: "Occupation was successfully updated." }
        format.json { render :show, status: :ok, location: @occupation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occupations/1 or /occupations/1.json
  def destroy
    @occupation.destroy

    respond_to do |format|
      format.html { redirect_to occupations_url, notice: "Occupation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occupation
      @occupation = Occupation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def occupation_params
      params.require(:occupation).permit(:user_id, :room_id, :day, :time_s, :time_e, :reservation, :confirmed)
    end
end

rvue/apps/app/helpers/occupations_helper.rb
module OccupationsHelper
end

rvue/apps/app/views/occupations/_form.html.erb
<%= form_with(model: occupation, class: "contents") do |form| %>
  <% if occupation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(occupation.errors.count, "error") %> prohibited this occupation from being saved:</h2>

      <ul>
        <% occupation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :room_id %>
    <%= form.text_field :room_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :day %>
    <%= form.date_field :day, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :time_s %>
    <%= form.datetime_field :time_s, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :time_e %>
    <%= form.datetime_field :time_e, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :reservation %>
    <%= form.check_box :reservation, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :confirmed %>
    <%= form.check_box :confirmed, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

rvue/apps/app/views/occupations/_occupation.html.erb
<div class="flex flex-col my-10">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <caption class="text-2xl font-bold py-4">予約状況</caption>
          <thead class="border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                部屋名
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                日付
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                開始時刻
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                終了時刻
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                予約確認
              </th>
            </tr>
          </thead>
          <tbody>
          <% @occupations.each do |occupation| %>
            <% tdcolor = occupation.day <= Date.today ? 'text-gray-300' : 'text-gray-900' %>
            <tr class="border-b">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium <%= tdcolor %>">
                <%= occupation.room.name %>
              </td>
              <td class="text-sm font-light px-6 py-4 whitespace-nowrap <%= tdcolor %>">
                <%= occupation.day.strftime("%Y年 %m月 %d日") %>
              </td>
              <td class="text-sm font-light px-6 py-4 whitespace-nowrap <%= tdcolor %>">
                <%= occupation.time_s.strftime("%R") %>
              </td>
              <td class="text-sm font-light px-6 py-4 whitespace-nowrap <%= tdcolor %>">
                <%= occupation.time_e.strftime("%R") %>
              </td>
              <td class="text-sm font-light px-6 py-4 whitespace-nowrap <%= tdcolor %>">
                <%= check_box_tag '','', occupation.reservation %>
              </td>
            </tr>
           <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

rvue/apps/app/views/occupations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing occupation</h1>

  <%= render "form", occupation: @occupation %>

  <%= link_to "Show this occupation", @occupation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to occupations", occupations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

rvue/apps/app/views/occupations/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">予約</h1>
  </div>

  <div class="wrapper bg-white rounded shadow w-full my-10">
    <div class="header flex justify-between border-b p-2">
      <span class="text-lg font-bold">
        <%= @today.strftime("%Y年 %m月") %>
      </span>
      <% nextmonth = (@today == Date.today) ? false : true %>
      <div class="buttons">
        <% if nextmonth %>
          <%= link_to(occupations_path(month: "prev"), class: "p-1") do %>
            <i class="text-green-300">←</i>
          <% end %>
          <i class="text-gray-300">→</i>
        <% else %>
          <i class="text-gray-300">←</i>
          <%= link_to(occupations_path(month: "next"), class: "p-1") do %>
            <i class="text-green-300">→</i>
          <% end %>
        <% end %>
      </div>
    </div>

    <table class="w-full">
      <thead>
        <tr>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">日</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">月</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">火</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">水</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">木</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">金</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">土</span>
          </th>
        </tr>
      </thead>
      <tbody>
      <% @weeks.each do |week| %>
        <tr class="text-center h-20">
        <% week.each do |day| %>
          <% this_month = (day.strftime("%m") == @this_month) ? true : false %>
          <% is_close    = (@day_enable[day] == :closed) ? true : false %>

          <td class="border <%= this_month ? '' : 'bg-gray-100' %> p-1 h-40 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 overflow-auto transition  duration-500 ease hover:bg-gray-300 ">
            <div class="flex flex-col h-40 mx-auto xl:w-40 lg:w-30 md:w-30 sm:w-full w-10 overflow-hidden">
              <div class="top h-5 w-full">
                <span class="text-gray-500"><%= day.strftime("%e") %></span>
              </div>
              <div class="bottom flex-grow h-30 py-1 w-full">
                <div class="<%= is_close ? 'bg-purple-900' : 'bg-blue-600' %> text-white rounded p-1 text-sm mb-1">
                  <span class="event-name">
                    <%= @day_enable[day] %>
                  </span>
                </div>
                <%= link_to '予約実施', new_occupation_path(day: day),
                    class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"  \
                    if !is_close %>
              </div>
            </div>
          </td>
        <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div>
    <%= render partial: "occupation", object: @occupations %>
  </div>

</div>

rvue/apps/app/views/occupations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New occupation</h1>

  <%= render "form", occupation: @occupation %>

  <%= link_to "Back to occupations", occupations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

rvue/apps/app/views/occupations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @occupation %>

    <%= link_to "Edit this occupation", edit_occupation_path(@occupation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this occupation", occupation_path(@occupation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to occupations", occupations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>