rvue/apps/config/routes.rb
Rails.application.routes.draw do
  resources :occupations
  resources :regulations
  resources :calenders
  devise_for :admins, controllers: {
        registration: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  devise_for :users, controllers: {
        registration: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"

end

rvue/apps/app/models/room.rb
class Room < ApplicationRecord
end

rvue/apps/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :profile)
    end
end

rvue/apps/app/helpers/rooms_helper.rb
module RoomsHelper
end

rvue/apps/app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :profile, style: "display: block" %>
    <%= form.text_area :profile %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rvue/apps/app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
    <p class="my-5">
        <strong class="block font-medium mb-1">ルーム名：</strong>
        <%= room.name %>
    </p>

    <p class="my-5">
        <strong class="block font-medium mb-1">詳細案内：</strong>
        <%= room.profile %>
    </p>
    <% if action_name != "show" %>
        <%= link_to "表示", room, class: "lnk_btn" %>
        <%= link_to '編集', edit_room_path(room), class: "lnk_btn ml-2" if admin_signed_in? %>
        <hr class="mt-6">
    <% end %>
</div>

rvue/apps/app/views/rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">ルーム編集</h1>
    <%= render "form", room: @room %>
    <%= link_to "表示", @room, class: "ml-2 lnk_btn" %>
    <%= link_to "戻る", rooms_path, class: "ml-2 lnk_btn" %>
</div>

rvue/apps/app/views/rooms/index.html.erb
<div class="w-full">
    <% if notice.present? %>
        <p class="alarm text-green-500" id="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
        <p class="alarm text-pink-500" id="alert"><%= alert %></p>
    <% end %>
    <div class="flex justify-between items-center">
        <h1 class="font-bold text-4xl">ルーム一覧</h1>
        <%= link_to '新規ルーム作成', new_room_path, class: "new_btn" if admin_signed_in? %>
    </div>
    <div id="rooms" class="min-w-full">
        <%= render @rooms %>
    </div>
</div>

rvue/apps/app/views/rooms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">新規ルーム</h1>
    <%= render "form", room: @room %>
    <%= link_to '戻る', rooms_path, class: "ml-2 lnk_btn" %>
</div>

rvue/apps/app/views/rooms/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
    <div class="mx-auto">
        <% if notice.present? %>
            <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
        <% end %>
        <%= render @room %>
        <%= link_to '編集', edit_room_path(@room), class: "mt-2 lnk_btn" %>
        <div class="inline-block ml-2">
            <%= button_to '削除', room_path(@room), method: :delete, class: "mt-2 lnk_btn" %>
        </div>
        <%= link_to '戻る', rooms_path, class: "ml-2 lnk_btn" %>
    </div>
</div>