rvue/apps/config/routes.rb
Rails.application.routes.draw do
  resources :occupations
  resources :regulations
  resources :calenders
  devise_for :admins, controllers: {
        registration: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  devise_for :users, controllers: {
        registration: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"

end

rvue/apps/app/views/layouts/_navi.html.erb
<nav class="bg-purple-900 text-white flex justify-between">
    <ul class="px-10 py-4 flex space-x-3">

        <%= content_tag(:li, class: "cursor-pointer") do link_to("HOME", root_path) end if !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("ルーム", rooms_path) end if admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("カレンダー", calenders_path) end if admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("就業規則", regulations_path) end if admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("予約", occupations_path) end if user_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("登録", new_user_registration_path) end if !user_signed_in? && !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("ログイン", new_user_session_path) end if !user_signed_in? && !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("管理者登録", new_admin_registration_path) end if !user_signed_in? && !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("管理者ログイン", new_admin_session_path) end if !user_signed_in? && !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("ログアウト", destroy_user_session_path, data: { turbo_method: :delete }) end if user_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do link_to("管理者ログアウト", destroy_user_session_path, data: { turbo_method: :delete }) end if admin_signed_in? %>

    </ul>
    <!-- .px-10 py-4 flex space-x-3 -->

</nav>
<!-- .bg-purple-900 text-white flex justify-between -->

rvue/apps/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ピグル</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'layouts/navi' %>
      <main class="container mx-auto mt-28 pt-5 flex">
          <%= yield %>
      </main><!--  .container mx-auto mt-28 pt-5 flex -->

  </body>
</html>